

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - env
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

secrets:
  env:
    file: .env

volumes:
  db_data:
