FROM node:20-alpine AS base

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances nécessaires pour Prisma
RUN apk add --no-cache libc6-compat

# Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./
COPY prisma ./prisma

# Installation des dépendances avec cache optimisé
RUN npm ci

# Générer les clients Prisma
RUN npx prisma generate

# Copier le reste du code source
COPY . .

# Exposer le port utilisé par l'application
EXPOSE 3000

# Commande pour démarrer l'application en mode développement
CMD ["npm", "run", "dev"]
