FROM node:23-alpine

WORKDIR /app

# Copie uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./
COPY prisma ./prisma

# Installation rapide et propre des dépendances
RUN npm ci

# Copie le reste du code (pour le dev, on peut tout copier)
COPY . .

EXPOSE 3000

# Lancement du mode dev (hot reload)
CMD ["npm", "run", "dev"]
