/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as InscriptionIndexRouteImport } from './routes/inscription/index'
import { Route as ConnexionIndexRouteImport } from './routes/connexion/index'
import { Route as TestcomponentsDatatableRouteImport } from './routes/testcomponents/datatable'
import { Route as ConnexionMotdepasseoublieIndexRouteImport } from './routes/connexion/motdepasseoublie/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ConnexionMotdepasseoublieCodeIndexRouteImport } from './routes/connexion/motdepasseoublie/code/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionIndexRoute = InscriptionIndexRouteImport.update({
  id: '/inscription/',
  path: '/inscription/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionIndexRoute = ConnexionIndexRouteImport.update({
  id: '/connexion/',
  path: '/connexion/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestcomponentsDatatableRoute = TestcomponentsDatatableRouteImport.update({
  id: '/testcomponents/datatable',
  path: '/testcomponents/datatable',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionMotdepasseoublieIndexRoute =
  ConnexionMotdepasseoublieIndexRouteImport.update({
    id: '/connexion/motdepasseoublie/',
    path: '/connexion/motdepasseoublie/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionMotdepasseoublieCodeIndexRoute =
  ConnexionMotdepasseoublieCodeIndexRouteImport.update({
    id: '/connexion/motdepasseoublie/code/',
    path: '/connexion/motdepasseoublie/code/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testcomponents/datatable': typeof TestcomponentsDatatableRoute
  '/connexion': typeof ConnexionIndexRoute
  '/inscription': typeof InscriptionIndexRoute
  '/signin': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/connexion/motdepasseoublie': typeof ConnexionMotdepasseoublieIndexRoute
  '/connexion/motdepasseoublie/code': typeof ConnexionMotdepasseoublieCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testcomponents/datatable': typeof TestcomponentsDatatableRoute
  '/connexion': typeof ConnexionIndexRoute
  '/inscription': typeof InscriptionIndexRoute
  '/signin': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/connexion/motdepasseoublie': typeof ConnexionMotdepasseoublieIndexRoute
  '/connexion/motdepasseoublie/code': typeof ConnexionMotdepasseoublieCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testcomponents/datatable': typeof TestcomponentsDatatableRoute
  '/connexion/': typeof ConnexionIndexRoute
  '/inscription/': typeof InscriptionIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/connexion/motdepasseoublie/': typeof ConnexionMotdepasseoublieIndexRoute
  '/connexion/motdepasseoublie/code/': typeof ConnexionMotdepasseoublieCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/testcomponents/datatable'
    | '/connexion'
    | '/inscription'
    | '/signin'
    | '/api/auth/$'
    | '/connexion/motdepasseoublie'
    | '/connexion/motdepasseoublie/code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/testcomponents/datatable'
    | '/connexion'
    | '/inscription'
    | '/signin'
    | '/api/auth/$'
    | '/connexion/motdepasseoublie'
    | '/connexion/motdepasseoublie/code'
  id:
    | '__root__'
    | '/'
    | '/testcomponents/datatable'
    | '/connexion/'
    | '/inscription/'
    | '/signin/'
    | '/api/auth/$'
    | '/connexion/motdepasseoublie/'
    | '/connexion/motdepasseoublie/code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestcomponentsDatatableRoute: typeof TestcomponentsDatatableRoute
  ConnexionIndexRoute: typeof ConnexionIndexRoute
  InscriptionIndexRoute: typeof InscriptionIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ConnexionMotdepasseoublieIndexRoute: typeof ConnexionMotdepasseoublieIndexRoute
  ConnexionMotdepasseoublieCodeIndexRoute: typeof ConnexionMotdepasseoublieCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription/': {
      id: '/inscription/'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion/': {
      id: '/connexion/'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testcomponents/datatable': {
      id: '/testcomponents/datatable'
      path: '/testcomponents/datatable'
      fullPath: '/testcomponents/datatable'
      preLoaderRoute: typeof TestcomponentsDatatableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion/motdepasseoublie/': {
      id: '/connexion/motdepasseoublie/'
      path: '/connexion/motdepasseoublie'
      fullPath: '/connexion/motdepasseoublie'
      preLoaderRoute: typeof ConnexionMotdepasseoublieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion/motdepasseoublie/code/': {
      id: '/connexion/motdepasseoublie/code/'
      path: '/connexion/motdepasseoublie/code'
      fullPath: '/connexion/motdepasseoublie/code'
      preLoaderRoute: typeof ConnexionMotdepasseoublieCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestcomponentsDatatableRoute: TestcomponentsDatatableRoute,
  ConnexionIndexRoute: ConnexionIndexRoute,
  InscriptionIndexRoute: InscriptionIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ConnexionMotdepasseoublieIndexRoute: ConnexionMotdepasseoublieIndexRoute,
  ConnexionMotdepasseoublieCodeIndexRoute:
    ConnexionMotdepasseoublieCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
